### ISSUE TITLE
Error when creating wallets

### ISSUE THREAD

**Issue by tbdng** [p2pderivatives/dlc#107]
dlccli wallets create \
    --conf ./conf/bitcoin.regtest.conf \
    --walletdir ./wallets/regtest \
    --walletname "alice" \
    --privpass "priv_alice" \
    --pubpass "pub_alice" \
    --seed "seed_alice" 

returns _Error: encoding/hex: invalid byte: U+0073 's'_

The problem is likely with the seed, as passing this command (from the print of create_wallets.sh) works

dlccli wallets create --conf ./conf/bitcoin.regtest.conf \
--walletdir ./wallets/regtest \
--seed 7fd197ec6220c015e99034dc9de9e58dd614e339f7cd28a1d6e2db79f336c165 \
--walletname alice \
--pubpass pub_alice \
--privpass priv_alice

**Comment by Jwata** [comment]
Yes, please replace it with your seed.
