### ISSUE TITLE
Error in create_dlc // change address not provided

### ISSUE THREAD

**Issue by tbdng** [p2pderivatives/dlc#108]
./test/cmd/create_dlc.sh runs until:

Creating DLC

dlccli contracts create --conf ./conf/bitcoin.regtest.conf --walletdir ./wallets/regtest --oracle_pubkey opub.json --fixingtime 2019-04-30T12:00:00Z --fund1 2000 --fund2 3333 --address1 bcrt1qzq0xgmnrw2gs0f7agm0saj39eupdzrpanv9d5c --address2 bcrt1qq0xp4wg37dreze6p90xva3nl6pevl205a483nx --fundtx_feerate 20 --redeemtx_feerate 20 --deals_file ./test/cmd/deals_qa.csv --refund_locktime 574196 --wallet1 alice --wallet2 bob --pubpass1 pub_alice --pubpass2 pub_bob --privpass1 priv_alice --privpass2 priv_bob

> Error: Change address must be provided by first party

__

From the create_dlc test it seems you commented out the chaddr creation?

```
chaddr1=""
chaddr2=""
# chaddr1=`$create_address $conf $walletdir $alicep_params`
# chaddr2=`$create_address $conf $walletdir $bobp_params`
# echo "change address1: $chaddr1"
# echo "change address2: $chaddr2"
```

**Comment by Jwata** [comment]
You need to provide an address to receive change when your utxo is grather than required amount.

**Comment by Jwata** [comment]
I tested without changes at the latest commit. So commented it out.
