### ISSUE TITLE
Error in deposit_fund.sh // the amount is too low

### ISSUE THREAD

**Issue by tbdng** [p2pderivatives/dlc#109]
The amounts created in deposit_funds.sh are too small, thus when one runs create_dlc.sh right after, it returns

`> Error: Not enough utxos from first party`

After passing a higher amount the create_dlc works just fine!

**Comment by Jwata** [comment]
That's weird. I tested the script recentlu. I will check the amounts defined in it.

**Comment by tbdng** [comment]
```
$bitcoincli sendtoaddress $addr_a 0.00011360
$bitcoincli sendtoaddress $addr_b 0.00012693
```
I changed to

**Comment by tbdng** [comment]
Sorry, I inadvertently closed the issue. Nonetheless, super small issue and easy fix.

T

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Jwata** [comment]
@tbdng 
I would appreciate if you create pull request that fix the scripts or documents :)
Thank you for your attention, anyway!

**Comment by tbdng** [comment]
Will do :) happy to start and contribute a bit!
